### ISSUE TITLE
Unable to resolve "react-native-screens" from "node_modules\react-navigation-stack\lib\module\views\StackView\StackViewCard.js" Failed building JavaScript bundle.

### ISSUE THREAD

**Issue by triloconinja** [creativetimofficial/now-ui-react-native#25]
> Unable to resolve "react-native-screens" from "node_modules\react-navigation-stack\lib\module\views\StackView\StackViewCard.js"
> Failed building JavaScript bundle.
> 

tried this solution but it doesnt work 

" removing node_module, .expo and package-lock.json and then reinstall all the packages and start the project by using the following command: expo r -c"

Node Version - v12.9.0

**Comment by Jaredude** [comment]
I had the same issue. Noticed that package.json in the repo is missing react-native-screens from the dependencies.

npm i react-native-screens
and you will be all set.

**Comment by groovemen** [comment]
Hello guys,

Thank you for using our products, and sorry for this inconvenience. We will fix this issue in the next update. 
@Jaredude, thanks for your quick solution.

All the best
Stefan

**Comment by BunthoeurnVann** [comment]
Error: Unable to resolve module `react-native-screens` from `node_modules\react-navigation-stack\lib\module\views\StackView\StackViewCard.js`: react-native-screens could not be found within the project.

**Comment by YoshiYo** [comment]
Same error here. Any news ?

**Comment by khuramdogar** [comment]
npm install --save react-native-gesture-handler react-native-reanimated react-native-screens

**Comment by ShizaSiddiqui** [comment]
yarn add react-native-gesture-handler react-native-reanimated react-native-screens

This worked for me.

**Comment by slothstronaut** [comment]
In my case the version I had in package.json was 2.0.0, simply running `expo install sentry-expo` upgraded to 2.1.2 and fixed the issue.

**Comment by ThierryLucDenichaud** [comment]
> 
> 
> I had the same issue. Noticed that package.json in the repo is missing react-native-screens from the dependencies.
> 
> npm i react-native-screens
> and you will be all set.

npm i react-native-screens@1.0.0-alpha.23

**Comment by de-saksham** [comment]
> Hello guys,
> 
> Thank you for using our products, and sorry for this inconvenience. We will fix this issue in the next update.
> @Jaredude, thanks for your quick solution.
> 
> All the best
> Stefan

Still facing the same issue, is there an update on this? @groovemen

**Comment by WardaFarhan** [comment]
Failed building JavaScript bundle.
Unable to resolve "./DishdetailComponent" from "components\MainComponent.js"

here the first file is called in main component and the second file is linked to app.js don't know how but both files are not interconnected.
I'm having this issue, have tried various methods but couldn't resolve it; anyone of you can solve this please.

**Comment by lopeselio** [comment]
Install React Navigation
`npm install react-navigation`

Install Dependencies
`expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view`

Install React Navigation Stack
`npm install react-navigation-stack @react-native-community/masked-view`

Start the app and clear cache with : `npm start -c`
Update Imports

imports  will  look like this:
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

Errors? If you are still seeing errors and complaints about packages, do the following:
`rm -r node_modules`
`rm package-lock.json`
`expo upgrade`
`npm start -c`

**Comment by lopeselio** [comment]
**The above^ works like wine...**

**Comment by palingheorghe** [comment]
This shouldn't be a problem anymore as this was solved by previous versions. If you still got any issues please take a look at @lopeselio s solution regarding the imports and removal of packaging. Thank you for your interest in our products!

**Comment by kirti210895swami** [comment]
> > Unable to resolve "react-native-screens" from "node_modules\react-navigation-stack\lib\module\views\StackView\StackViewCard.js"
> > Failed building JavaScript bundle.
> 
> tried this solution but it doesnt work
> 
> " removing node_module, .expo and package-lock.json and then reinstall all the packages and start the project by using the following command: expo r -c"
> 
> Node Version - v12.9.0

First you have to check which version is supporting, in my case I used this command
"npm i react-native-screens@2.2.0"
When I m using " npm i react-native-screens"
- actual version installed: ^2.16.1
- react-native-screens - expected version range: ~2.2.0

**Comment by Al-Imran420** [comment]
I had same issues and fixed it by install some necessary module. Run the command below in your terminal fixed this issues completely...:)
**npm install --save react-native-gesture-handler react-native-reanimated react-native-screens**

**Comment by manuelmhtr** [comment]
I had to do `yarn cache clean` after removing `node_modules`.
