### ISSUE TITLE
Converting Expo to React native cli 

### ISSUE THREAD

**Issue by jadhavrahul10** [creativetimofficial/now-ui-react-native#26]
Hi team,

i am having subscription of creative tim i wanted to convert this expo project to react native.
if you have any guide lines please share

**Comment by groovemen** [comment]
Hello @jadhavrahul10,

Thank you for your interest in our products! We’re sorry to hear you have any issues with our product. Our project is based on Expo and we usually don’t recommend ejecting. If you do eject, certain problems may occur so solving them would take a while. Do you want to eject via Bare or Expokit? You might have to delete certain files that you can read more about here: https://docs.expo.io/versions/latest/bare/using-expo-client/#avoid-importing-the-expo-package-in-bare. Be sure to not have any ‘expo’ packages imported in any file. 

These are official guides from Expo which we recommend reading: - this is for ejecting to ExpoKit https://docs.expo.io/versions/latest/expokit/eject/ and this is for ejecting to Bare https://docs.expo.io/versions/latest/workflow/customizing/.  

I hope some of this information is going to help you.
All the best, 
Stefan

**Comment by Joshua-alt** [comment]
**Converting Expo to React native cli** 
All you need is to copy your components folder and screen folder or your src folder of the expo project into
your react-native project and install all packages that you are used in your expo project
