### ISSUE TITLE
Not able to clone in snack.expo.io directly via url 

### ISSUE THREAD

**Issue by saadahmadabbasi** [creativetimofficial/now-ui-react-native#28]
Getting following message when i am trying to import git repo in snack, i have changed SDK to use 36:

An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project.

**Comment by leonoronhas** [comment]
Same with me...

**Comment by palingheorghe** [comment]
Hope you solved your issue! Thank you for your interest in our products! I'll close the issue for inactivity as this didn't get much traction.
