### ISSUE TITLE
Downloading JavaScript bundle 100% stuck

### ISSUE THREAD

**Issue by khoirunalim** [creativetimofficial/now-ui-react-native#29]
I have issues after adding `await` on `Font.loadAsync({
      'montserrat-regular': require('./assets/font/Montserrat-Regular.ttf'),
      'montserrat-bold': require('./assets/font/Montserrat-Bold.ttf'),
    });` 

I've been restarting `react-native debugger` but still not work, what should I do ?

npm ver 6.14.5
expo ver 3.12.5
expo client ver 2.15.4
PC windows 10
Android ver 9 
device Xiaomi A1

**Comment by palingheorghe** [comment]
This shouldn't be a problem anymore as this was solved by previous versions. Thank you for your interest in our products!
