### ISSUE TITLE
Does not build in expo Web

### ISSUE THREAD

**Issue by JUDOKICK** [creativetimofficial/now-ui-react-native#31]
When trying to launch this template and the argon one. Both do not run in the Expo Web setup. 

They are met with

"Uncaught SyntaxError: Unexpected Token '!'" And react-native-web missing deps.

Is there any workaround to this ?

**Comment by palingheorghe** [comment]
Hi @JUDOKICK this product has never been built with the purpose of running on web. All the necessary steps for that need to be coded by you. Thank you for being interested in our products!
