### ISSUE TITLE
Unable to resolve "react-native-gesture-handler" from "node_modules/react-navigation/node_modules/@react-navigation/native/lib/module/Scrollables.js"

### ISSUE THREAD

**Issue by usamaatta** [creativetimofficial/now-ui-react-native#32]

**Comment by palingheorghe** [comment]
This is a common error that should have been solved by now. If yours isn't solved please follow the next steps as this means your cache is pretty full of old stuff: 
After updating to our latest version, go into your project's folder and write the following command in the terminal: 
- `rm -rf node_modules`
- `rm -rf .expo`
- `rm -rf package-lock.json`
- `npm i`
- `expo r -c` 

This should restart and clear your cache which should solve the problem easily.

Thanks!
