### ISSUE TITLE
Reason: Cannot find module 'firebase\package.json'

### ISSUE THREAD

**Issue by hunterperatt** [creativetimofficial/now-ui-react-native#33]
PLEASE HELP!!!! I have been stuck on this error for days and days and can not figure it out.
I am using a managed expo environment in react native and can not get firebase to work...
This is the error I get when I start metro bundler (npm start)

warn Package firebase has been ignored because it contains invalid configuration. Reason: Cannot find module 'firebase\package.json'
Require stack:
- C:\Users\hunte\FlyExpo\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- C:\Users\hunte\FlyExpo\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
- C:\Users\hunte\FlyExpo\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\runServer.js
- C:\Users\hunte\FlyExpo\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\start.js
- C:\Users\hunte\FlyExpo\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\hunte\FlyExpo\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\hunte\FlyExpo\node_modules\react-native\local-cli\cli.js

App.js
import React from "react";
import WelcomeScreen from "./app/screens/WelcomeScreen";
import "react-native-gesture-handler";
import * as firebase from "firebase";

src = "https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js";

var firebaseConfig = {
  apiKey: "*************************",
  authDomain: "*************************",
  databaseURL: "*************************",
  projectId: "*************************",
  storageBucket: "*************************",
  messagingSenderId: "*************************",
  appId: "*************************",
  measurementId: "*************************",
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);
firebase.analytics();

export default function App() {
  return <WelcomeScreen />;
}

package.json 
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^8.4.2",
    "@react-native-firebase/auth": "^9.2.2",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "apisauce": "^1.1.2",
    "axios": "^0.20.0",
    "date-fns": "^2.16.1",
    "expo": "~38.0.8",
    "expo-font": "^8.2.2",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.2",
    "expo-updates": "~0.2.8",
    "firebase": "7.9.0",
    "install": "^0.13.0",
    "lodash": "^4.17.20",
    "native-base": "^2.13.14",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-platform-touchable": "^1.1.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.7",
    "react-native-screens": "^2.9.0",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^2.15.1",
    "react-native-unimodules": "~0.10.1",
    "react-native-vector-icons": "^7.0.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.4.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-axios-middleware": "^4.0.1",
    "redux-persist": "^6.0.0",
    "rm": "^0.1.8",
    "victory-native": "^35.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}

**Comment by palingheorghe** [comment]
Thank you for using our products! People are already discussing problems with firebase at #27 . Please ask and read through the messages there. 

Thanks!
